Flipkart_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  join_position_controller:
    type: effort_controllers/JointPositionController
    joint: [Revolute_1, Revolute_2, Revolute_3, Revolute_4] 
    pid: {p: 100.0, i: 0.01, d: 10.0}


